In [27]:
# Linear prediction estimation: https://www.youtube.com/watch?v=NtTYdYffalY
# https://www.youtube.com/watch?v=ZqpSb5p1xQo

"""Use linear prediction estimation to predict values of a sample. 
Identify the residuals of the difference between this prediction and
the original sample. Write the coefficients of the prediction and the
residuals as the output. The residuals should be encoded using 
Exponential Golomb encoding 
(https://www.youtube.com/watch?v=roGtuW4pNac). This encoding method will
use less bits for values that are smaller. If the residuals are often small, 
this will result in a greater compression ratio potentially. 
"""

IndentationError: unexpected indent (3627298524.py, line 4)

In [2]:
import librosa
import scipy
import numpy as np
import logging
from importlib.util import spec_from_loader, module_from_spec
from importlib.machinery import SourceFileLoader

# import encode 
spec = spec_from_loader("encode", SourceFileLoader("encode", "./encode"))
encode = module_from_spec(spec)
spec.loader.exec_module(encode)

file = 'data/0ab237b7-fb12-4687-afed-8d1e2070d621.wav'

input_wav = encode.read_file(file)
lpc_order = 10


In [12]:
y, sr = librosa.load(file)

In [16]:
y

array([0.04933495, 0.05901925, 0.04806332, ..., 0.04215939, 0.04258398,
       0.        ], dtype=float32)

In [17]:
a = librosa.lpc(y=y, order=lpc_order)

In [18]:
a

array([ 1.        , -1.3745602 ,  1.0743389 , -1.2038124 ,  1.2227042 ,
       -1.2176883 ,  1.0748787 , -0.9384279 ,  0.7152793 , -0.52670133,
        0.19240542], dtype=float32)

In [26]:
a

array([ 1.        , -1.3745602 ,  1.0743389 , -1.2038124 ,  1.2227042 ,
       -1.2176883 ,  1.0748787 , -0.9384279 ,  0.7152793 , -0.52670133,
        0.19240542], dtype=float32)

In [22]:

print(a)
s_hat = scipy.signal.lfilter([0] + -1*a[1:], [1], y)
s_err = y[1:] - s_hat[:-1]
print(s_hat)
print(s_err)

[ 1.         -1.3745602   1.0743389  -1.2038124   1.2227042  -1.2176883
  1.0748787  -0.9384279   0.7152793  -0.52670133  0.19240542]
[ 0.06781386  0.02812305  0.06204928 ...  0.05086675  0.0320873
 -0.00855744]
[-0.00879461  0.01994027 -0.01460078 ...  0.01806241 -0.00828277
 -0.0320873 ]


In [24]:
print(len(s_err))
type(s_err)

111476


numpy.ndarray